apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 02-configmap.yaml
  - 03-secrets.example.yaml
  - 04-vault.yaml
  - 05-minio.yaml
  - 06-bootstrap-jobs.yaml
  - 07-api.yaml
